export enum WalletType {
    Bitcoin = 'Bitcoin',
    Ethereum = 'Ethereum',
    BSC = 'BSC',
    Avalanche = 'Avalanche',
    Solana = 'Solana',
    Cardano = 'Cardano',
    ETHZKsync = 'ETHZKsync',
    Tron = 'Tron',
    Arbitrum = 'Arbitrum',
    Polygon = 'Polygon',
    Optimism = 'Optimism',
    Fantom = 'Fantom',
    Cronos = 'Cronos',
    Algorand = 'Algorand',
    Osmosis = 'Osmosis',
}
